---
- name: Deploy Kubernetes 
  hosts: all
  become: true
  tasks:
    - name: Copy Jar Files to Kubernetes Master
      copy:
        src: target/spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar
        dest: /root/target/
    - name: Copy Dockerfile to Kubernetes Master
      copy:
        src: Dockerfile
        dest: /root/
    - name: Copy Deployment File to Kubernetes Master
      copy: 
        src: deployment.yaml
        dest: /root/
    - name: Delete deployent (if any)
      command: kubectl delete --ignore-not-found=true -f /root/deployment.yaml
    - name: Build Docker container locally
      shell: |
        cd /root
        docker build -t darrenchooji/springpetclinic:latest .
    - name: Create new deployment 
      command: kubectl apply -f /root/deployment.yaml
